### ISSUE TITLE
Disable ERROR and WARN messages in console app

### ISSUE THREAD

**Issue by Airn5475** [KevM/tikaondotnet#101]
I am using TikaOnDotNet in a console app.  There are many ERROR and WARN messages that appear as I parse a variety of documents.
Here are just two examples:
`ERROR OpenType Layout tables used in font ABCDEE+Times New Roman are not implemented in PDFBox and will be ignored`
`WARN No Unicode mapping for CID+58 (58) in font Arial-ItalicMT`

Is there any way to disable these messages?  They are taking over my output window!

**Comment by ErikOmberg** [comment]
You'll need this:
using java.io;
using org.apache.commons.io.output;

Then, add this line to your c# code:
java.lang.System.setErr(new PrintStream(new NullOutputStream()));

**Comment by Airn5475** [comment]
Thank you! That did the trick!

**Comment by KevM** [comment]
This feels like it might want to be documented. Anyone want to submit a PR for this?

**Comment by TechnikEmpire** [comment]
@KevM When you ask for these documentation PR's, where exactly would stuff like this and #97 etc be documented? Developers.md? I briefly started fishing through contrib guide etc trying to sort that out but I'm lazy so I thought I'd just ask.

**Comment by KevM** [comment]
@TechnikEmpire thanks for thinking about this. Where to put this information is a bit tricky because the text extractor nuget docs is where this belongs but this project has no separate repo for that add-on. I think maybe for now the best place would be to enhance the `readme.md` with a FAQ or getting started section for the TextExtractor nuget. What do you think of this?

**Comment by TechnikEmpire** [comment]
@KevM they're kind of odd ball things that I think would be best categorized in a FAQ or pitfalls section or something. Seems kind of out of place to slap into the readme no? What about doing a section like a FAQ on the GitHub pages and then referencing it in the readme, or maybe just drop this stuff into the wiki?

**Comment by KevM** [comment]
Sounds fine to me. Can you do this?

**Comment by TechnikEmpire** [comment]
@KevM sure when I have a few minutes of down time. So GitHub pages plus readme or wiki?

**Comment by TechnikEmpire** [comment]
That should say GitHub pages plus readme, or just drop it in wiki? I'm assuming the former.

**Comment by KevM** [comment]
Hmm, I think the GitHub pages are currently geared for a landing page rather than where to go for documentation. So maybe a wiki page would be better. I just turned on the wiki feature for this repo.

**Comment by TechnikEmpire** [comment]
Cool sounds good. Does the wiki come down in PRs? Never tried. If it does I'll fork and document the outstanding stuff sometime in the next few days I gotta clear some work off my plate first.

**Comment by KevM** [comment]
You can just create pages and edit them at will.
