### ISSUE TITLE
Support Tika 1.15

### ISSUE THREAD

**Issue by Sicos1977** [KevM/tikaondotnet#102]
Support Tika 1.15

**Comment by KevM** [comment]
Thanks. Didn't know it had come out. If you want to follow the release
guide I'll be happy to accept the PR. Otherwise I'll try to get to it when
I can. I am on vacation.

**Comment by Sicos1977** [comment]
I will look into it morning evening.

Also another thing, it seems that the developer of IKVM has decided to stop with it.

 

Greetings,

Kees van Spelde

 

Van: Kevin Miller [mailto:notifications@github.com] 
Verzonden: maandag 19 juni 2017 19:39
Aan: KevM/tikaondotnet <tikaondotnet@noreply.github.com>
CC: Kees <magic-sessions@home.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [KevM/tikaondotnet] Support Tika 1.15 (#102)

 

Thanks. Didn't know it had come out. If you want to follow the release
guide I'll be happy to accept the PR. Otherwise I'll try to get to it when
I can. I am on vacation.

**Comment by TechnikEmpire** [comment]
Yes we all know IKVM has been abandoned. Was mentioned in another bug ticket by kev

**Comment by KevM** [comment]
Closed as I released both 1.15 and 1.16 today. Enjoy!
