### ISSUE TITLE
ios pages support

### ISSUE THREAD

**Issue by Nazgaul** [KevM/tikaondotnet#103]
I see that Tika support ios pages (.pages) but the code doesnt extract the text. can you please add

**Comment by KevM** [comment]
Can you explain what you need? Better would be to write a failing test with
a .pages file you wish to parse.

**Comment by KevM** [comment]
Clone the project. Check out the unit tests. Add a test for the file you
wish to be parsed. Add the file to the files folder. See the test fail.
Create a PR with the failing test.

**Comment by KevM** [comment]
stale
