### ISSUE TITLE
Tika is missing methods

### ISSUE THREAD

**Issue by EdS0ng** [KevM/tikaondotnet#107]
I have installed the latest TikaOnDotNet (v1.16) from Nuget. When I try to access the setExtractBookmarksText method on PdfParserConfig, which is documented in the Tika api, Visual Studio cannot find such a method.  However, when i built Tika using IKVM myself and used it in my project, the methods are available.  I downloaded Tika from here -> http://www.apache.org/dyn/closer.cgi/tika/tika-app-1.16.jar.

Anyone know why this is happening? My understanding was that this latest version of TikaOnDotNet is using Tika 1.16.

**Comment by KevM** [comment]
Are you building the .Net Tika assembly yourself or are you consuming our Nuget?

Regarding method missing. Can you give us more detail? What method is missing? There are some problems #105 with pdf rendering and IKVM missing implementations of java methods.

**Comment by EdS0ng** [comment]
So I initially consumed your Nuget package. However, that package is missing the SetExtractBookmarksText method on the PDFParserConfig class. Sorry i can't give you a link, the Tika docs don't generate a good url. All the method does is configure the pdf parser to extract text from bookmarks or not, so it does not have to do with imaging.

I then built the .Net Tika assembly myself to check if the issues is from IKVM. When using my own built assembly, the missing method is there. I downloaded the Tika .jar from their download link on the Tika website and just ran it through ikvmc.

**Comment by TechnikEmpire** [comment]
@KevM I'm a jerk for saying I'd write up info about those issues and not doing it, my bad. I'll try to get to that soon. I did some checking on some of my own forks though and I'm not sure that the wiki syncs between forks so maybe we have to build it into readme.md's here?

Also @EdS0ng Can you post in the exact stack trace for this issue? I'm aware of methods missing in IKVM directly related to IO with PDF images, so there's a good chance your missing method exception is the same, rooted in IKVM.

**Comment by EdS0ng** [comment]
This is what I'm trying to do, where PDFParser is a type provided from Tika.
_extractor = new PDFParser();
_extractor.getPDFParserConfig().setExtractBookmarksText(false);

The error is not a runtime error as it can't even get past build.
'PDFParserConfig' does not contain a definition for 'setExtractBookmarksText' and no extension method 'setExtractBookmarksText' accepting a first argument of type 'PDFParserConfig' could be found (are you missing a using directive or an assembly reference?)

Currently i can workaround by replacing the TikaOnDotNet dll with my own built version and it works fine.

**Comment by KevM** [comment]
Sorry you are having problems. Can you write a failing test?

I'm curious about the release you are using. How is it different that what
we use? The .jar we use is at this URL. http
http://www-us.apache.org/dist/tika/tika-app-1.16.jar

**Comment by EdS0ng** [comment]
I tried building using the tika jar from your link. it is also fine. I'm using IKVM version 8.1.5717.0 if that makes a difference. 

What do you mean by failing test?

**Comment by KevM** [comment]
stale
