### ISSUE TITLE
Not able to build the project

### ISSUE THREAD

**Issue by surajsokasane** [KevM/tikaondotnet#110]
I cloned the repository but not able to build the same.
Getting below errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'C:\Users\Suraj\Source\Repos\tikaondotnet\src\TikaOnDotnet.TextExtractor\..\..\SolutionInfo.cs' could not be found.	TikaOnDotnet.TextExtraction	C:\Users\Suraj\Source\Repos\tikaondotnet\src\TikaOnDotnet.TextExtractor\CSC	1	Active

Someone please help.

**Comment by KevM** [comment]
Did you follow the readme instructions?

**Comment by surajsokasane** [comment]
No, I'm sorry. Is it included in repo?

**Comment by KevM** [comment]
https://github.com/KevM/tikaondotnet/blob/master/Developers.md
