### ISSUE TITLE
Upgrade to Tika 1.17

### ISSUE THREAD

**Issue by nixa333** [KevM/tikaondotnet#112]
Hi there,

are you planning to upgrade to Tika 1.17?

**Comment by KevM** [comment]
Thanks for letting me know [1.17 is out](https://tika.apache.org/1.17/index.html).

Do you want to create a PR for it? There [is a guide on how to do it](https://github.com/KevM/tikaondotnet/blob/master/Developers.md#updating-ikvm). 💃

**Comment by nixa333** [comment]
I have to say I'm not skilled with the procedures around pulling Git repos(never did this before), but I tried following the guide. When I try to push new version on newly created branch 1.17 I get an error:

git push origin 1.17 --tags
remote: Permission to KevM/tikaondotnet.git denied to nixa333.
fatal: unable to access 'https://github.com/KevM/tikaondotnet.git/': The requested URL returned error: 403

Do you have to grant me permissions to be able to do this?

**Comment by KevM** [comment]
Thank you for trying! I think you should create a PR.
https://help.github.com/articles/creating-a-pull-request/ And then I'll
merge it and tag the release and your contribution will have created a 1.17
nuget. I'll try to update the contribution docs with this detail.

**Comment by KevM** [comment]
Looks like I already have some [guidance there](https://github.com/KevM/tikaondotnet/blob/master/Contributing.md#a-new-version-of-tika-came-out).

**Comment by nixa333** [comment]
Done.
