### ISSUE TITLE
Cant read from RAR files.

### ISSUE THREAD

**Issue by vuralvard** [KevM/tikaondotnet#122]
Your project is working just fine but when I try to read from RAR files , I get this error "Unexpected RuntimeException from org.apache.tika.parser.pkg.RarParser@1eb99a9". Thanks!

**Comment by KevM** [comment]
Hard to say if this is an IKVM problem or a Tika problem. You might want to try Tika with Java and see if you have the same problem. Let me know what you use as a work around.

**Comment by vuralvard** [comment]
Thanks for the respond. I will be trying, if I can solve the problem, I will share the solution. peace!

**Comment by vuralvard** [comment]
I solved the prob. It doesnt extract text from winrar 5.0+ versions. Trying with wrar extraction version with 2.9 solved. ty

**Comment by KevM** [comment]
Thanks for the update. I wonder why 5.0 breaks things. ☹️
