### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by catmanjan** [KevM/tikaondotnet#159]
Last Nuget package was in 2018 (now 5 years ago)

Shouldn't there be new changes, or is the software "done"?

**Comment by KevM** [comment]
If you checkout the [this PR](https://github.com/KevM/tikaondotnet/pull/152) you'll see a group of people are working to make this project work against dotnet core. The .Net Framework version in theory works but has not been updated. If you'd like to step up and work through the issues getting it working on dotnet core. I'm sure there would be a crowd that is appreciative.
