### ISSUE TITLE
IKVM fixed version dependency

### ISSUE THREAD

**Issue by ltrzesniewski** [KevM/tikaondotnet#18]
Currently, the NuGet package depends on IKVM = 7.4.5196. Could it be made to depend on IKVM >= 7.4.5196 instead?

I'm using TikaOnDotNet along with other NuGet packages which also have a dependency on IKVM. I'd like to update these, but the fixed IKVM version dependency prevents me from doing so easily.

The change should be simple enough, and should be fully backwards-compatible:

    <dependencies>
      <dependency id="IKVM" version="7.4.5196" />
    </dependencies>

(just remove the brackets around the version number)

Thanks.

**Comment by KevM** [comment]
@ltrzesniewski Happy to do this. If you submit a PR it will get done a lot faster. :boat:

**Comment by ltrzesniewski** [comment]
Sure, thanks, here you go.

**Comment by ltrzesniewski** [comment]
FYI, I wanted to test this and... the current Tika version doesn't seem to play very well along with IKVM 8, so I'll wait for 1.7 ;)

**Comment by KevM** [comment]
Are you saying that the latest IKVM Nugets do not work very well? Should we revert this commit?

**Comment by KevM** [comment]
@ltrzesniewski are you saying that this project is now broken on the latest IKVM? What problems are you seeing? Do you think we should revert this commit and re-release?

**Comment by ltrzesniewski** [comment]
This lib still works when installed standalone (I just tested this), because NuGet resolves the IKVM dependency to version 7.4.5196, just as before.

But if you try to update IKVM to v8, it breaks (I've got *method not found* in a test project, but a different error in my real project). I think Tika needs to be recompiled with IKVM 8 for it to work on IKVM v8.

I'd advise a version dependency like this: **7.4.5196 <= IKVM version < 8.0**

    <dependency id="IKVM" version="[7.4.5196,8.0.0)" />

**Comment by KevM** [comment]
OK I understand. You might be able to fix your problem with an assembly redirect if the Nuget update didn't do one for you.

**Comment by ltrzesniewski** [comment]
Nope, that's not the issue. IKVM just changed too much internally for the redirect to do any good. So did OpenJDK I suppose.

A Tika version cross-compiled with IKVM 7 doesn't seem to play along very well when used with IKVM 8 assemblies. Honestly, that's not really a surprise.

**Comment by KevM** [comment]
OK if you want to push a PR for that change you get the cookie. Or else I'll do it later and post a new Nuget.

**Comment by ltrzesniewski** [comment]
That would be a fix for #20 actually. Unfortunately I don't have much time right now either... I'll try to do this later unless you overtake me on this :stuck_out_tongue_winking_eye:

**Comment by KevM** [comment]
New Nuget 1.12.0 [was released ](https://github.com/KevM/tikaondotnet/releases/tag/v1.12.0)
