### ISSUE TITLE
Recursive processing with TikaOnDotNet

### ISSUE THREAD

**Issue by emrobi** [KevM/tikaondotnet#26]
I am attempting to process nested docs using the example code from: http://wiki.apache.org/tika/RecursiveMetadata.

The key seems to be setting up the context with context.set(Parser.class, parser); since somewhere down in the Tika code it will pull out that class object with context.get(Parser.class).

In .NET, Parser is an interface and has no 'class' property. 

What do I use on the .Net side so that the converted java code works correctly?

**Comment by emrobi** [comment]
This works:

            var parser = new RecursiveMetadataParser(new AutoDetectParser());
            var context = new ParseContext();
            context.set(typeof(Parser), parser);

**Comment by KevM** [comment]
Thanks for letting us know you found a fix. :+1:
