### ISSUE TITLE
"The decryption operation failed" during install-package

### ISSUE THREAD

**Issue by dellwilson** [KevM/tikaondotnet#32]
1. Created a command line project.
2. Install-Package TikaOnDotNet

install-package : The decryption operation failed, see inner exception.
At line:1 char:1
+ install-package TikaOnDotNet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by KevM** [comment]
Are you still having this problem? Can you check if you still have troubles with the [new release](https://github.com/KevM/tikaondotnet/releases/tag/v1.12.0)?

**Comment by dellwilson** [comment]
Thanks for the response. No issues installing the latest packages. Thanks again.
