### ISSUE TITLE
Version ?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [KevM/tikaondotnet#34]
Is this librarys version linked with the Tika version somehow? If not, would be nice.

**Comment by KevM** [comment]
I am, now, doing my best to keep it in sync. Working on getting Nugets to be published by CI. Please note the new (upcoming) 1.12 release has [breaking changes](https://github.com/KevM/tikaondotnet/blob/master/Release-Notes.md#1120) if you are using `TextExtractor`.

**Comment by bjorn-ali-goransson** [comment]
A good idea, I think, is to reserve only the Major&Minor numbers for communicating the Tika version, reserving the Revision number for own updates. Everytime Tika comes out with a patch, updating the Revision number, you would increase your own Revision number by one to indicate an update, but not necessarily keeping it in sync with Tika.

**Comment by KevM** [comment]
Thanks. That is basically my plan.
