### ISSUE TITLE
NuGet package 1.12

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [KevM/tikaondotnet#40]
Hi,

Are you sure that the TikaOnDotNet assemblies got included in the latest build? I can't seem to find either TikaOnDotNet or TextExtractor anymore...

**Comment by KevM** [comment]
Note this release had a breaking change. You need to take a dependency on [TikaOnDotNet.TextExtractor](https://www.nuget.org/packages/TikaOnDotnet.TextExtractor/)

**Comment by bjorn-ali-goransson** [comment]
Good job on the CI rework, thanks for this.

**Comment by bjorn-ali-goransson** [comment]
I might add that I saw this package before, but since it mentioned the phrasing Example, I did not think of installing it ...
