### ISSUE TITLE
Reference discrepancy?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [KevM/tikaondotnet#41]
When installing the .TextExtractor package with dependencies on an empty project, I get the message:

    Assembly 'TikaOnDotNet' with identity 'TikaOnDotNet, Version=1.12.0.0, Culture=neutral, PublicKeyToken=null'
    uses 'IKVM.OpenJDK.Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58'
    which has a higher version than referenced assembly 
    'IKVM.OpenJDK.Core' with identity 'IKVM.OpenJDK.Core, Version=7.2.4630.5, Culture=neutral, PublicKeyToken=13235d27fcbfff58'

When examining the TikaOnDotNet nupkg nuspec, I find that the dependency is in fact `<dependency id="IKVM" version="[7.2.4630.5]" />`.

I have no wierd assemblyRedirects (I actually cleared them just to be sure), and IKVM is installed on the said project with the "correct" version. No other project is using it.

Upgrading the NuGet package manually does it, so this is a bug report.

**Comment by bjorn-ali-goransson** [comment]
Also, I have not installed using "ignore dependencies" either...

**Comment by KevM** [comment]
Try clearing your packages directory as a workaround. I will look into this.

**Comment by bjorn-ali-goransson** [comment]
On top of this, my NUnit3 does not seem to acknowledge my assembly redirects... 

![upload](https://cloud.githubusercontent.com/assets/668160/14445595/9a4340e2-004e-11e6-8247-707002313558.png)

**Comment by KevM** [comment]
I am on a tablet at the moment. As soon as I can build and verify I'll be getting a new revision released.

**Comment by bjorn-ali-goransson** [comment]
Actually, I never installed `TikaOnDotNet` specifically. I thought just by installing the `.TikaTextExtraction`, NuGet would handle the dependency resolving by itself. But it seems this hasn't happened because of the default setting of `Dependency handling: Lowest`.

Thus, if I download only the TextExtraction package, it will pick the "lowest possible" compatible version of the `TikaOnDotNet` package, which isn't specified (I'd say here's the problem), so it installs `TikaOnDotNet.1.6.4.51427`, which isn't compatible because of the referenced DLLs.

What do you say?

**Comment by bjorn-ali-goransson** [comment]
Recommended solution would be to set the minimum version of the `1.12.x` packages to be `> 1.12.0`, in the nuspec.

**Comment by bjorn-ali-goransson** [comment]
I can confirm that everything works as expected when updating all packages :+1:

**Comment by KevM** [comment]
Ok thank you for the helpful reporting.

**Comment by bjorn-ali-goransson** [comment]
This is nitpicking but I think it is not perfect quite yet:

- `TikaOnDotNet 1.12.1` was fixed by adding a versioned dependency on IKVM (= 8.1.5717)
- But `.TextExtractor` is not yet dependent on this version, by using NuGet default settings we will not get `TikaOnDotNet 1.12.1` by installing the latest `.TextExtractor`.

I think that we should bump both packages to `1.12.2`, `.TextExtractor` having a dependency of `TikaOnDotNet (> 1.12.2)`. THEN we will force the tested-to-be-compatible packages to go together.

If one does want to try something else, he will have to check "Ignore Dependencies" in NuGet to go wild.

**Comment by KevM** [comment]
Sigh. #42 will remove the coupling the two projects have. There is no reason they need to be versioned together. Another compatibility concern is #47.
