### ISSUE TITLE
TextExtractor should be versioned separately 

### ISSUE THREAD

**Issue by KevM** [KevM/tikaondotnet#42]
Now that they have been separated. Should TextExtractor be in a completely different repo? 

The two Nugets should at least have separate Release notes and version numbers.

**Comment by bjorn-ali-goransson** [comment]
:+1:

**Comment by KevM** [comment]
@bjorn-ali-goransson Which do you like better separate repos or release notes. Separate repos would remove the wonky local reference I have and let the two things evolve better separately.

**Comment by bjorn-ali-goransson** [comment]
@KevM Separate repos could be better, yes. If it's not overkill for you that is.

**Comment by KevM** [comment]
It should be no big deal. Just have to carve out the time.
