### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by harrchen** [KevM/tikaondotnet#49]
tried to build the source with build.cmd.  My source is located at c:\users\harrchen\source\repos\tikaondontnet.  However, got error pointing to c:\code which doesn't exist:
  1) System.Exception: Could not run "git rev-parse HEAD".
Error: Start of process git.exe failed. The system cannot find the file specified
   at Fake.Git.CommandHelper.runSimpleGitCommand@89-2.Invoke(String message) in C:\code\fake\src\app\FakeLib\Git\CommandHelper.fs:line 89
![tikaondotnet_builderror](https://cloud.githubusercontent.com/assets/18751110/14935795/acef5012-0eab-11e6-80e8-6d3f78361dc8.PNG)

**Comment by KevM** [comment]
Did you download the code or clone the repo? The build assumes you are in a git repo to add the current commit SHA to the assembly info.

**Comment by harrchen** [comment]
I cloned the repo from visual studio 2015 and run the build.cmd from the command line.

**Comment by KevM** [comment]
Ok. Do you have git installed in your path? 
Try `git -v`. In any case I should make that part of the build automation more resilent.

**Comment by harrchen** [comment]
Thanks.  I am able to build the TikaOnDotnet now from the Visual studio 2015 after removing the SolutionInfo.cs reference from project file.

 

However, I do get one warning when I ran the solution to parse a few documents:

“WARNING: PooledTimeSeries not installed!”

Not sure if this is something I need to take care of or can be ignored.

 

Overall, very nicely done project.  Thanks a lot for the work and sharing.

 

Harry

**Comment by KevM** [comment]
Looks like someone ran into this again. Let's work on this problem on #52. Marked that issue up for grabs if anyone wants to address it.
