### ISSUE TITLE
Where is SolutionInfo.cs?

### ISSUE THREAD

**Issue by harrchen** [KevM/tikaondotnet#50]
The project has a link to SolutionInfo.cs but that file is not part of the source.  Is it needed?  If so, where I can find it?

**Comment by KevM** [comment]
Build the app from the command line. If the readme doesn't already say this it should.

**Comment by KevM** [comment]
https://github.com/KevM/tikaondotnet/blob/master/Readme.md

**Comment by harrchen** [comment]
When I tried to use build.cmd, I ran into other issues (also submitted).  I finally just removed the SolutionInfo.cs reference from project and it built fine with Visual Studio.

**Comment by KevM** [comment]
This is a duplicate of #49.
