### ISSUE TITLE
I am having the same issue, but  built it outside of visual studio 2012.

### ISSUE THREAD

**Issue by aahock** [KevM/tikaondotnet#51]
I also get the 'HEAD' error.  You say I am supposed to have 'git' installed?  Where do I get 'git'? I don't see any place to download 'git' for .NET.  There are 5 or 6 .NET add-ins that reference 'git'.  Which one do I use?  I have never used git before, except to download zips and use things.  I really would like to also use this in a project, but already had an issue with:

The build is referencing a jar file that is x.12 and it receives a 404 error.  The jar file is actually x.13.  I could fix that in the build file and continue.  But I cannot get past the 'git' issue.  Please help!

**Comment by KevM** [comment]
Looks like the ReadMe could use some improvement.
- Mention the git requirement and [how to install git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) if you don't already have it.

**Comment by KevM** [comment]
@aahock Looks like you opened another issue for the same problem #52 I think the best solution is to update the readme and work towards making the build not care if git is missing.
