### ISSUE TITLE
Add a strong name to the dlls

### ISSUE THREAD

**Issue by Oddleif** [KevM/tikaondotnet#58]
Not signed with strong names, which means it's not possible to reference them from other dlls having a strong name. Also unable to re-sign them using ILDASM/ILASM, hence it's a bit of pain...

Please sign the dlls with a strong name.

**Comment by KevM** [comment]
Thanks for the suggestion. I don't currently have a need for this change but I am happy to have it included if others want to take it on:

- Add support to the FAKE build scripts to [sign assemblies](http://fsharp.github.io/FAKE/apidocs/fake-signtoolhelper.html) when key is present. If you want to do a powershell scripts that is fine too. Whatever works and can be called by Appveyor as part of the release process.
- Add encrypted key to source control for local or [CI signing by Appveyor)[http://help.appveyor.com/discussions/questions/217-signing-net-assemblies-without-exposing-the-snk-file-publicly}

**Comment by smkuls** [comment]
Is there any way as of today that this DLL could be referred from other DLLs having a strong name?

**Comment by KevM** [comment]
Build your own version and sign it. Pretty common practice where this is
required. I am happy to take a pull request adding this capability.

**Comment by smkuls** [comment]
So I ran the build.cmd which generated the TikaOnDotNet.dll in the lib folder. I signed it (the DLL properties show a digital signature). However, the sn.exe tool still shows that the DLL does not represent a strongly named assembly. Am I missing something here?

**Comment by KevM** [comment]
My usualy experience with signing is as part of the build process not afterwards. There is [delay signing](https://msdn.microsoft.com/en-us/library/t07a3dye(v=vs.110).aspx) but you still need to prepare the assembly for it. I think the FAKE script could be updated to [add the assembly attribute needed](http://fsharp.github.io/FAKE/apidocs/fake-assemblyinfofile-attribute.html). Then afterward you can use the [sign tool](http://fsharp.github.io/FAKE/apidocs/fake-signtoolhelper.html) as you are.

**Comment by KevM** [comment]
I bet the real problem is that the Tika assembly built via `ikvmc.exe` is not being signed. 

http://www.ikvm.net/userguide/ikvmc.html

**Comment by Sicos1977** [comment]
You can sign assembly's that is build with IKVM. I also did that before.

Greetz..
