### ISSUE TITLE
TextExtractor.Extract(byte[] data) should accept offset and length

### ISSUE THREAD

**Issue by ctstone** [KevM/tikaondotnet#59]
This function should handle byte array offset and length for when the data buffer is larger than the actual document it contains.

Something similar to `Encoding.GetString(byte[] bytes, int index, int count)`

**Comment by KevM** [comment]
Howdy. Sorry for the long delay. Would you like to submit a PR for this? I'd be happy to help out with it.

**Comment by KevM** [comment]
I looked into this a bit and the extensibility is there for this to be added via a handy extension method:

```cs
public static class TextExtractorExtensions
{
    public static TextExtractionResult Extract(this TextExtractor textExtractor, byte[] data, int index, int count)
    {
        var bytes = data.Skip(index).Take(count).ToArray();
        return textExtractor.Extract(metadata => TikaInputStream.get(bytes, metadata));
    }
}
```

Let me know what you think. I tried to provide Extracts for typical situations and the `Func<Metadata, InputStream>` version for extensibility.
