### ISSUE TITLE
Some OpenJDK assemblies were not copied?

### ISSUE THREAD

**Issue by xdvarpunen** [KevM/tikaondotnet#61]
https://sourceforge.net/p/ikvm/bugs/296/

Files are not found for some reason in Extractor class

**Comment by xdvarpunen** [comment]
I couldn't get newest release working. 1.7.0 is working perfectly though.

java.io.File file = new java.io.File("C:/asdf.txt");
org.apache.tika.Tika tika = new org.apache.tika.Tika();
System.Console.WriteLine(tika.ToString());
                String filetype = tika.detect(file);
                System.Console.WriteLine(filetype);

**Comment by KevM** [comment]
You are using the TikaApp assembly directly? Have you tried using the TextExtractor nuget?

**Comment by xdvarpunen** [comment]
Yes; I am using following NuGets: 
* IKVM v8.1.5717
* TikaOnDotnet v1.13.1
* TikaOnDotnet v1.13.1

**Comment by xdvarpunen** [comment]
Okey I think I might have found some clues...

I am using following setup; PCL with TikaOnDotnet that is called into Console project. When I call PCL with all NuGets up to date I face the problem. When I call method and have NuGets straight installed inside the Console project I face no errors.

**Comment by xdvarpunen** [comment]
Strangely enough when I have in both projects installed TikaOnDotnet but I call the PCL project Extract method I see the errors but no exception/console application crash happens.

**Comment by KevM** [comment]
I don't know much about PCL projects. Anyone care to educate me about how
this is different than plain old .Net? Could it be that IKVM is simply now
PCL compatible?

**Comment by KevM** [comment]
@xdvarpunen Can you setup a sample project where you are running into this problem? I'd like to see if I can help Tika run in desired environments.

**Comment by KevM** [comment]
I believe IKVM dependencies and nuget dependency problems have been fixed. If you are taking a dependency on TikaOnDotNet.TextExtractor you should be fine.

Regarding PCL support if someone needs this please open an issue and we can investigate.
