### ISSUE TITLE
Feeding Tika with a stream?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [KevM/tikaondotnet#65]
Hello again.

Is there much to gain by using this method, instead of feeding Tika a simple byte array?

`public TextExtractionResult Extract(Func<Metadata, InputStream> streamFactory);`

If so, how do we use it?

Right now, my code looks like this:

```
    public List<string> ExtractText(Stream inputStream)
    {
        using (var memoryStream = new MemoryStream())
        {
            inputStream.CopyTo(memoryStream);

            var result = Tika.Extract(memoryStream.GetBuffer());

            var str = result.Text
                .Replace("\r", string.Empty)
                .Replace("§  ", string.Empty)
                .Split(new string[] { "\n\n\n\n" }, StringSplitOptions.RemoveEmptyEntries)
                .Select(t => t.Replace("\n", " ").Replace("    ", " ").Replace("   ", " ").Replace("  ", " ").Trim())
                .ToList();

            return str;
        }
    }
```

**Comment by KevM** [comment]
@bjorn-ali-goransson are you trying to extract from Tika directly to an output stream to avoid memory usage? The reason why I've used memory in the past is that we were turning around and feeding the text Lucene. I could see a usage where you stream it directly up to Solr or to a file on disk.

**Comment by bjorn-ali-goransson** [comment]
For example, when using Azure Blobs, all you get is a stream - so storing
it in an array first just to feed it into Tika would be the taking long way
around.

2016-12-15 2:08 GMT+01:00 Kevin Miller <notifications@github.com>:

**Comment by KevM** [comment]
Oh good. Thanks for the use case. I think #74 might solve your concern. Please do take a look. I could use feedback to see if this addresses your concern.

**Comment by KevM** [comment]
All done and merged.
