### ISSUE TITLE
Reason why IKVM is omitting some methods?

### ISSUE THREAD

**Issue by TechnikEmpire** [KevM/tikaondotnet#66]
What could be a possible reason for IKVM to omit certain methods? Looking at the class:

`org.apache.fontbox.encoding.Encoding`, you get this from metadata:

```C#
#region Assembly tika-app, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// <in-memory assembly>
#endregion

using IKVM.Attributes;
using java.lang;
using java.util;

namespace org.apache.fontbox.encoding
{
    public abstract class Encoding : Object
    {
        public const int NUMBER_OF_MAC_GLYPHS = 258;
        [Signature("Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;")]
        public static Map MAC_GLYPH_NAMES_INDICES;
        [Signature("Ljava/util/Map<Ljava/lang/Integer;Ljava/lang/String;>;")]
        protected internal Map codeToName;
        [Signature("Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;")]
        protected internal Map nameToCode;

        [LineNumberTableAttribute(new[] { 159, 174, 232, 160, 78, 203 })]
        public Encoding();

        [Modifiers(Modifiers.Public | Modifiers.Static | Modifiers.Final)]
        public static string[] MAC_GLYPH_NAMES { get; }

        [LineNumberTableAttribute(new[] { 160, 97, 113, 131, 130 })]
        public static string getCharacter(string name);
        public static void __<clinit>();
        [LineNumberTableAttribute(199)]
        [Throws(new[] { "java.io.IOException" })]
        public virtual string getCharacter(int code);
        [LineNumberTableAttribute(new[] { 92, 114, 131, 159, 16 })]
        [Throws(new[] { "java.io.IOException" })]
        public virtual int getCode(string name);
        [LineNumberTableAttribute(new[] { 111, 119, 131, 134 })]
        [Throws(new[] { "java.io.IOException" })]
        public virtual string getName(int code);
        [LineNumberTableAttribute(new[] { 159, 97, 66, 118, 131, 159, 16 })]
        [Throws(new[] { "java.io.IOException" })]
        public virtual string getNameFromCharacter(char c);
        [LineNumberTableAttribute(new[] { 77, 115, 115 })]
        protected internal virtual void addCharacterEncoding(int code, string name);
    }
}
```
But if we look at the method summary table from the [docs](https://pdfbox.apache.org/docs/2.0.2/javadocs/org/apache/fontbox/encoding/Encoding.html) (either [1.8.x](https://pdfbox.apache.org/docs/1.8.10/javadocs/org/apache/pdfbox/encoding/Encoding.html) or [2.0.x](https://pdfbox.apache.org/docs/2.0.2/javadocs/org/apache/fontbox/encoding/Encoding.html#getCodeToNameMap())), you can see there are methods such as:

```java
Map<Integer,String>	getCodeToNameMap()
Returns an unmodifiable view of the code to name mapping.
```

I've seen this behaviour on other libs I was tinkering with yesterday, but the methods/classes showed up if I exported the jar differently before running it through IKVM. Looking for your thoughts and thanks in advance.

**Comment by TechnikEmpire** [comment]
Sorry to be a bother, I guess Visual Studio Code is choking on resolving things correctly, or I have my project misconfigured. I recreated the project in VS2015 and the methods are showing up.

**Comment by KevM** [comment]
Great. Thanks for letting us know. Maybe this will help others down the
road.

**Comment by TechnikEmpire** [comment]
@KevM Hopefully. Another FYI, the PDF capabilities of this library are severely limited due to a bug in IKVM. IKVM completely omitted some core image reading functions, so you can't do anything related to reading (I assume also writing?) images to/from PDF files. It just crashes and there's no way around it, because they intentionally throw "Not Implemented" from each of these methods. You'd have to hack apart IKVM, implement those methods (there's a few missing) to fix that. I also tried building Pdfbox-App myself, hacking it apart to avoid these methods and you just can't get around them being called. I know this isn't your problem, it's IKVM's, and I know this lib does so much more, but just a heads up.

**Comment by KevM** [comment]
Hmm. Could you try building a version of TikaOnDotNet that links to the older version of IKVM? Maybe this is a regression in the [very old release candidate](http://weblog.ikvm.net/)?

**Comment by TechnikEmpire** [comment]
@KevM There's a detailed thread here from someone else who hit the same roadblock as me. https://sourceforge.net/p/ikvm/mailman/message/35356915/ It's just IKVM devs did not implement graphics related JDK methods that are essential to working with images in PDFs.
