### ISSUE TITLE
Update to latest Tika version

### ISSUE THREAD

**Issue by Sicos1977** [KevM/tikaondotnet#67]
Hi,

Can you update to the latest version? Version 1.14 is out since 19 October,

Thanks.

**Comment by KevM** [comment]
There is a how to on this if you want to make a PR. I would love to get
feedback from someone else doing this to help improve the documentation.

https://github.com/KevM/tikaondotnet/blob/master/Readme.md

**Comment by Sicos1977** [comment]
I have a look into tomorrow... does not seem to be to difficult to do and I did use IKVM more then once :)

**Comment by Sicos1977** [comment]
I looked into Tika a few years back and then decided to use iFilters --> https://github.com/Sicos1977/IFilterTextReader ... but Tika has made some big improvements last year so looking into Tika again.

**Comment by KevM** [comment]
Thank you. It should be turn key. It is all automated. Let me know if you
have any pain.

**Comment by Sicos1977** [comment]
Hi,

I did build the new version and tried to push it but that gives me this error:

C:\Users\Kees\Documents\GitHub\tikaondotnet [master ≡ +0 ~4 -0 !]> git push origin --tags
remote: Permission to KevM/tikaondotnet.git denied to Sicos1977.
fatal: unable to access 'https://github.com/KevM/tikaondotnet.git/': The requested URL returned error: 403
C:\Users\Kees\Documents\GitHub\tikaondotnet [master ≡ +0 ~4 -0 !]>

**Comment by Sicos1977** [comment]
There is also a typo in you code... I think StringExtrensions should be StringExtensions (without the R)

**Comment by KevM** [comment]
You don't have push access to the repo. Can you [create a Pull Request?](https://help.github.com/articles/creating-a-pull-request/)

**Comment by KevM** [comment]
>  typo in you code

Thanks. Go ahead and fix it in an separate PR.

**Comment by Sicos1977** [comment]
O well that I have to start over again because I now just cloned to my local drive and not to Github.

**Comment by Sicos1977** [comment]
Also a thing for your build script..

Add this line:

./paket update

Because the paket.lock needs to be updated when I update the link to the new tika jar.

**Comment by KevM** [comment]
>  I now just cloned to my local drive and did not do a fork on Github.

You can always fork it on the website and then [add the remote manually](https://help.github.com/articles/adding-a-remote/). 

> Because the paket.lock needs to be updated when I update the link to the new tika jar.

I think all that is needed is `./paket.exe install` (like a nuget restore) which I believe is done for each build. 

[paket update](https://fsprojects.github.io/Paket/paket-update.html) will update dependencies not simply download them.

**Comment by KevM** [comment]
Checked and `paket restore` is being done by the `build.cmd`. Let me know where the docs could be improved to avoid this ambiguity.

**Comment by Sicos1977** [comment]
Hi,

Sorry for the delay but I had some other things that kept me busy.
I added this line to your build.sfx file:

**Comment by Sicos1977** [comment]
Nice automation... seems all went well and the new package is also pushed to NuGet

**Comment by KevM** [comment]
@Sicos1977 To help everyone could you create a PR for the two things you did? 
- Update Tika version
- Add assembly signing

**Comment by KevM** [comment]
Derp. You already did. Just in one PR. Thanks.
