### ISSUE TITLE
DotNet core porting

### ISSUE THREAD

**Issue by frankabbruzzese** [KevM/tikaondotnet#75]
Is the last december 2016 TikaOnDotNet release compatible with dotnet core? If not are there plans to port  TikaOnDotNet to the dotnet core platform?

**Comment by KevM** [comment]
Not sure. It has a good chance of being compatible with .Net standard 2.0 but I have not done the research yet. It really depends on IKVM.

**Comment by Sicos1977** [comment]
I don't think it will be compatible because IKVM converts java code to .NET code and the latest IKVM version is older then the first .NET core release..... but you can always try it out :-)

**Comment by KevM** [comment]
Yes. I am a bit worried about IKVM there is a large [bus factor](https://en.wikipedia.org/wiki/Bus_factor) there.

**Comment by frankabbruzzese** [comment]
No I think IKVM is not compatible .Net core. There is already a [porting request](https://sourceforge.net/p/ikvm/feature-requests/38/), but none is answering. I added my +1 :)

**Comment by Sicos1977** [comment]
If you want to see a nice video about the programmer of IKVM then go here --> https://channel9.msdn.com/Blogs/Charles/E2E-Erik-Meijer-and-Jeroens-Frijters-IKVMNET-Java-VM-implemented-in-NET

**Comment by KevM** [comment]
With IKVM losing the support of the original developer. 

http://weblog.ikvm.net/default.aspx?month=2017-04#a33ea525f-a291-418a-bd6a-abdf22d0662b

This may not materialize any time soon. Closing this issue for the short term.

**Comment by TechnikEmpire** [comment]
Aw snap. #RIPinpeace some of my own projects. Thanks for sharing that link @KevM
