### ISSUE TITLE
New upgrade generates VS errors

### ISSUE THREAD

**Issue by alrehamy** [KevM/tikaondotnet#80]
Nuget latest distribution : 

Assembly 'TikaOnDotNet,  uses 'IKVM.OpenJDK.Text  Version=8.1.5717.0 which has a higher version than referenced assembly 'IKVM.OpenJDK.Text, Version=7.2.4630.5

Also

Assembly 'TikaOnDotNet.TextExtraction, Version=1.14.0.0 uses 'IKVM.OpenJDK.Core, Version=8.1.5717.0 which has a higher version than referenced assembly 'IKVM.OpenJDK.Core, Version=7.2.4630.5.

**Comment by KevM** [comment]
I confirmed this and fixed it and will be publishing a nugget shortly. Thanks for the report!

**Comment by KevM** [comment]
Nuget 1.14.1 is released.
