### ISSUE TITLE
Newbie: memory issues and console output

### ISSUE THREAD

**Issue by afederici75** [KevM/tikaondotnet#81]
Hi and thank you for the wonderful job with TikaOnDotnet.
This is the first time I am trying to use anything that works on top of IKVM and I have a few of issues/questions I could use guidance with. I tried to research the current issues, but I could not find anything that helps me.

1) Somehow when a document conversion fails, I get error messages and call-stacks straight into my Console window. How do I tell IKVM or Tika not to output there? I would love to redirect errors to my logger (which is *not* Log4Net but Gurock's SmartInspect), not the Console.

2) Somehow after running conversions for about 5 or 6 hours (we have hundreds or thousands of documents to process) my machine's hard disk was left with 0 bytes of space left. The machine I am referring to is not storing the source documents and is not the place where I dump the extracted text. I am guessing that somehow some large dump file is created because of the errors I receive with some documents, but I have not yet found where all the disk space is going. A reboot of the machine released many Gbs of lost disk space... Is IKVM or Tika creating log files? If it is, how do I tell it either a) not to or b) control how big such files can become and where they get stored?

3) I am sporadically getting errors such as those in the following file (which I hope got attached to this post): [Errors.txt](https://github.com/KevM/tikaondotnet/files/709348/Errors.txt)

Stuff like
1) TikaException: Unexpected RuntimeException from org.apache.tika.parser.pdf.PDFParser@172ce77
2) TikaException: Unexpected RuntimeException from org.apache.tika.parser.microsoft.OfficeParser@1e60d0
3) IllegalArgumentException: The end (982) must not be before the start (996)  (MANY of these)

How can I figure out what causes them or where should I ask about such issues?

Thanks a lot!
Alessandro Federici

**Comment by TechnikEmpire** [comment]
I can at least help answer #1. You need to set java.lang.System.setOut(...)
and googling about capturing the console output on Java will yield results
that include a class template you can supply as an argument to that
function.

**Comment by KevM** [comment]
> A reboot of the machine released many Gbs of lost disk space... Is IKVM or Tika creating log files?

Are you seeing a memory or disk usage problem? I don't know why rebooting would clean up disk space. It would fix memory usage problems. My experience with using Tika to index large amounts of documents has been to ensure the machine has plenty of memory and surely run in a 64 bit process as it is easy to hit 2GBs of memory usage. I never had a problem with disk space usage other than log files I was producing on purpose. 

> I am sporadically getting errors such as those in the following file

My guess for these would be problems with Tika parsing documents is common and can be frustrating. I would try to confirm that I get the same error for the same file consistently. I used to have common problems with old Office file formats throwing exceptions and sometimes PDFs that were poorly created. I had my indexer catch Tika exceptions and do what I could for files like these. If you have files with problems that you can share I would highly recommend you submitting them to the Tika project as a bug. You could share the files with us too and we could make a failing test for them and see when a new version of Tika fixes them.

**Comment by afederici75** [comment]
Thanks TechnikEmpire! 
I ended up making a NullPrintStream grabbing some ideas from here.
http://stackoverflow.com/questions/4799006/in-java-how-can-i-redirect-system-out-to-null-then-back-to-stdout-again

**Comment by TechnikEmpire** [comment]
@afederici75 Just wondering if you have any feedback regarding @KevM 's questions. Would help the project out to be able to reproduce your other issues or at least be able to test when the issues are fixed upstream in the Tika project, assuming that's where the issue lies.

**Comment by afederici75** [comment]
Damn guys, I am so sorry I disappeared! I totally lost track of this (got swamped in other fires)....

In regards to KevM's: I gave it one more try, just to get more info on what was chewing hard disk space, but the problem *seems* to have gone away. I will rerun the bulk and try to get more info, but the virtual memory swap seemed not to have grown and the other folders I kept an eye on (Windows, Java, my service, Program files) were fine too. I will retry again a few times this week, but maybe something completely different was going on (and yes, it's something I've never seen before in my life either <G>).

As far as those "bad" documents are concerned, I am gonna have to see if I can alter one so that it does not show any customer data but still has the issue. If I can manage to do that, I would love to send it to you, so you can see what is going on.

Finally, in regards to the setOut() thingie. It works with my direct Console.print() (or whatever the Java exact method is called), but somehow, while those bad documents appear, the log text is still outputed to the Console. I am wondering if somewhere the Tika code resets the out() or if the Console I have access to (in my thread) might be different from Tika's?

Once again, apologies for having disappeared,
  Alessandro Federici

**Comment by afederici75** [comment]
I could reproduce the disk space issue again: it was due to the virtual memory swap file becoming huge

**Comment by KevM** [comment]
Thanks for letting us know. It sounds like your solution there is more memory. Tika loves memory. You could also try streaming your content. The latest release of text extractor can directly output extracted text to a Stream. Check out [this merge commit for usage examples](https://github.com/KevM/tikaondotnet/commit/a7a76ec44312006568f875b717fcf89ffd33e8a9)).

**Comment by afederici75** [comment]
Hi,
  here are a couple of files that we can share with you and that give us one of those funky errors ('The end (X) must not be before the start (Y)'). If you unzip the contents of the file I attached to this post and try to extract the text in such files, you should see the error.

[For Tika.zip](https://github.com/KevM/tikaondotnet/files/764946/For.Tika.zip)

**Comment by afederici75** [comment]
Any luck with the attachment above?

**Comment by rbower54** [comment]
Hi,
I'm running into a small issue with TikaOnDotNet where we've parsed in some *.doc documents that contain quoted strings and apostrophes such as:  
Robert's famous quote of "I Love TikaOnDotNet" and some more words that follow it.  
The parsing will result in the following literal results: 
Robert famous quote of Love TikaOnDotNetand some more words to follow it.  
It strips the apostrophe and double quotes and the characters/spaces which follow them.
Any guidance would be greatly appreciated!
Thanks

**Comment by KevM** [comment]
Thanks for the upload. I confirmed these files have problems with Tika's office parser. This does not seem related to TikaOnDotnet but rather Tika's OfficeParser which uses POI I believe. I'd report this issue to them for the greatest chance of correction. 

https://tika.apache.org/contribute.html

I have some tests written on a branch and I'll check them out next time Tika releases an update. I think 1.15 is around the corner.

**Comment by KevM** [comment]
Side note I do not have Microsoft Office so I tried uploading these files to Google Docs and was able to see an approximation of what the contents should look like.

**Comment by afederici75** [comment]
Thanks!
