### ISSUE TITLE
Extracted words not intact - they get broken up

### ISSUE THREAD

**Issue by rjaitly** [KevM/tikaondotnet#82]
I extracted words from a word document and it is breaking up word with a line wrap. The word doc has the line "This is a test doc2" and it breaks up the "doc2" into "doc" + linefeed + "2". Why is this?

After extraction it looks like:
This is a test doc
2

[test101.docx](https://github.com/KevM/tikaondotnet/files/717786/test101.docx)

**Comment by KevM** [comment]
Not really sure. Does the doc have any styling changes between the characters?

**Comment by rjaitly** [comment]
I had attached the document to my original post.

**Comment by KevM** [comment]
I do not use word

**Comment by rjaitly** [comment]
no, it does not have any styling changes. It just has the one line "This is a test doc2". Prior to this I had tried to extract from a larger word document and noticed this problem with multiple other words, I therefore created this smaller document to repro the issue so that I could post here. We currently use DTSearch and this problem doesn't happen with DTSearch. I came across your post while searching for cheaper alternatives to DTSearch and decided to test it out.

BTW, if you do not use word, you can still view word documents by creating a free account on our site www.filesanywhere.com and uploading the document and viewing it through the site while you are logged in.

**Comment by KevM** [comment]
@rjaitly Please take a look at the PR #93 I just posted and let me know if this corrects your problem.

**Comment by rjaitly** [comment]
Since your changes have not been committed yet, what do I need to do to get your changes into my project to see if it has corrected the problem?

**Comment by TechnikEmpire** [comment]
@rjaitly See nuget:
https://www.nuget.org/packages/TikaOnDotNet/1.14.2-pre
In your project enable pre-release and install that version.

**Comment by rjaitly** [comment]
This is weird. I just ran the project as is without getting the pre-release version and I am unable to repro the issue which I originally reported. I have no explanation for it at all.

**Comment by TechnikEmpire** [comment]
@rjaitly It's because I'm so amazing at teh codez that I fix bugs just by getting near them. On a serious note, same code, same input etc?

**Comment by rjaitly** [comment]
everything is the same. I just thought I would repro the issue once before getting the pre-release to see the fix. But, now I am unable to repro. I even checked to see that none of the files are checked out, and that the date time stamps of all the project files and the referenced files have not changed. I am at a loss to explain why I cannot repro the issue. The only thing I can think of is that some windows referenced component/dll may have been the real cause of the issue and has got replaced in my windows auto updates.
