### ISSUE TITLE
Problem with RTF extraction

### ISSUE THREAD

**Issue by HolisticMystic** [KevM/tikaondotnet#83]
I am new to adding java directly to my VS project, but a very old hand at VS development.
I was running some tests using the files found in the files folder of the downloadable project.
(I am new to GitHub also. You can think of me as a slave who has been chained in a basement doing advanced client/server projects for the last ten years and I have just been freed).
Anyways, I had great results with all but two of the extraction types.
Let's talk about the rtf first. The code I ran was as follows:
`        Try
            fileext = ".rtf"
            TextBox1.AppendText("Extracting - " & filepath & fileext & Environment.NewLine)
            res = rip.Extract(filepath & fileext)
            For Each m In res.Metadata
                TextBox1.AppendText(m.Key & " = " & m.Value & Environment.NewLine)
            Next
            TextBox1.AppendText("Text - " & res.Text & Environment.NewLine)
            TextBox1.AppendText("*****" & Environment.NewLine)
        Catch ex As TextExtractionException
            TextBox1.AppendText(ex.Message & Environment.NewLine & ex.Source & Environment.NewLine)
        End Try
`     
This worked (incredibly) on all files except the RTF. It printed the first line and then silently failed to print the rest to the textbox. I could break and view the value of 'res.Text' and see that the text (which included a lot of white space) was all there.  I tried several things that didn't work and suspect that it may have to do with encoding. Any hints you might share?

**Comment by HolisticMystic** [comment]
I ran some code from MSDN on value of res.Text. The code was from https://msdn.microsoft.com/en-us/library/kdcak6ye(v=vs.110).aspx?cs-save-lang=1&cs-lang=vb#code-snippet-1
Once I had extracted res.Text and converted the text to a Unicode Byte array I saw that bytes 17 thru 255 were blank. Converting that back to Ascii bytes showed bytes 9 thru 127 were blank (duh). It could be that the converter is 'giving up' after reading so many blank bytes. Going to try my own rtf file and try to keep the empty bytes to a minimum. Be right back.

**Comment by HolisticMystic** [comment]
Hmmm. Created rtf file with two lines of unadorned text, followed by a line with a jpg image pasted in, and a fourth line of unadorned text. My code returned the first line of text. Formatting the second half of the first line as a slightly larger Garamond font caused the returned text to end where the new formatting began. Looks like your text_extraction.cs file needs several dozen new 'cases' to test. As I said though, very nice. Keep up the good work. I am running this on VS2013 v.12.0.30723.00 Update 3 using .Net4.5 The platform is Windows 7 Ultimate SP1 on an ASUS ROG notebook (SOTA 2 years ago). Still going to use this code in my project (I don't have that many RTF files to worry about it. One last thing to note: the preview panel in Windows 7 Explorer shows only the first two lines (even after formatting added) and does not show the image or the fourth line of text. Hope any of this helps.

**Comment by KevM** [comment]
Could you create a test with your .rtf file so we can see about fixing the problem?

**Comment by HolisticMystic** [comment]
Tomorrow, for sure.

Night is getting a bit long now.

Talk to you soon.

Thanks,

Mitch Bird

 

  _____

**Comment by HolisticMystic** [comment]
Although the dialog says I can drag and drop or select a zip file ... it lies.
Email me directly and I can forward you a project.

**Comment by KevM** [comment]
@HolisticMystic Can you [create a PR](https://help.github.com/articles/creating-a-pull-request/) with the file added to our [unit test files](https://github.com/KevM/tikaondotnet/tree/master/src/TikaOnDotNet.Tests/files)?

**Comment by KevM** [comment]
@HolisticMystic Please take a look at the PR #93 I just posted and let me know if this corrects your problem.

**Comment by KevM** [comment]
@HolisticMystic another ask for the .rtf file giving you problems. Please attach it to this issue and I'll take a look.

**Comment by KevM** [comment]
Closing this if you have more information please create a new issue and link to this one.
