### ISSUE TITLE
Apostrophe and Double Quote Parsing Issue

### ISSUE THREAD

**Issue by rbower54** [KevM/tikaondotnet#86]
Hi,
I'm running into a small issue with TikaOnDotNet where we've parsed in some *.doc documents that contain quoted strings and apostrophes such as:
Robert's famous quote of "I Love TikaOnDotNet" and some more words that follow it.
The parsing will result in the following literal results:
Robert famous quote of Love TikaOnDotNetand some more words that follow it.
It strips the apostrophe and double quotes and the characters/spaces which follow them.
Any guidance would be greatly appreciated!
Thanks

**Comment by rbower54** [comment]
?

**Comment by KevM** [comment]
I've been busy with work. Do you think you can write up a failing test? Have you [asked the Tika project](https://lists.apache.org/list.html?user@tika.apache.org) for assistance?

**Comment by KevM** [comment]
Not sure but I think this may be related to how our content handler is handling the quotes in content.

**Comment by KevM** [comment]
@rbower54 Please take a look at the PR I just posted and let me know if this corrects your problem.

**Comment by afederici75** [comment]
Hi KevM, I work with rbower54 and wanted to test this, but we download this component using NuGet from VS. I am not sure how to get a build of the package(s) that has this fix in: the stuff VS shows seems rather old (January).

**Comment by KevM** [comment]
I uploaded a pre-release nuget. Go ahead and give it a try.

https://www.nuget.org/packages/TikaOnDotnet.TextExtractor/1.14.2-pre
