### ISSUE TITLE
Importing Tikaondotnet with Nuget package

### ISSUE THREAD

**Issue by abhi004** [KevM/tikaondotnet#87]
I tried adding Nuget package for Tikaondotnet but getting exception 

Assembly 'TikaOnDotNet.TextExtraction' with identity 'TikaOnDotNet.TextExtraction, Version=1.14.1.0, Culture=neutral, PublicKeyToken=fd70f0f601f583f3' uses 'IKVM.OpenJDK.
Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58' which has a higher version than referenced assembly 'IKVM.OpenJDK.Core' with identity 'IKVM.OpenJDK.Core, Version=7.2.4630.5
, Culture=neutral, PublicKeyToken=13235d27fcbfff58'

**Comment by KevM** [comment]
Hello, I just created a new project. And added a Nuget reference to TikaOnDotNet.TextExtraction and was able to use it without problem.

```cs
using System;
using TikaOnDotNet.TextExtraction;

namespace tikatest3
{
    class Program
    {
        static void Main(string[] args)
        {
            var extractionResult = new TextExtractor().Extract(new Uri("https://wikipedia.org"));

            Console.WriteLine(extractionResult.Text);
        }
    }
}
```

Can you give us more information about how you are using the text extractor or how exactly you added the Nuget dependency?

**Comment by andreasnauta** [comment]
Hi,

I got the same error when I created an ASP.NET Core Web Application (.NET Framework) project in VS2017. Updating to the latest pre-release solved this for me.

I tried creating an ASP.NET Web Application (.NET Framework) project as well. I got the same issue, but it was solved by updating as well.

Best regards,
Andreas

**Comment by KevM** [comment]
I think the problem is that TextExtractor needs to declare it's required TikaOnDotNet dependency version and then things are happy.
