### ISSUE TITLE
Apache Tika can not read text in correct sequence from multilayered PDF file.

### ISSUE THREAD

**Issue by rekhatiwarigeniusminds** [KevM/tikaondotnet#94]
Apache Tika can not read text in correct sequence from multilayered PDF file. . The sequence of extracting content for multilayered pdf is not correct. It cannot extract images from pdf as well. Could you suggest me how I might achieve the above, preferably with some code examples using TikaOnDotNet.
Here is the multilayered pdf link  for your reference:
https://www.dropbox.com/s/c0y4kt7usnlicb1/SampleDoc.pdf?dl=0

**Comment by TechnikEmpire** [comment]
The ordering in any PDF is not guaranteed, AFAIK, it's just a series of rendering operations going on inside the file in no particular order. I had to write several algorithms using OpenCV and the text positions of all individual extracted characters to visually determine text groupings, then order those text groupings logically (in my case it was all left to right ordering).

This is very complex, and in fact my own algorithms heavily rely on having foreknowledge of the proper ordering to a degree. PDFBox, like every other pdf library I've tried, simply makes a "best guess" at ordering and doesn't consider half the factors I mentioned above. Plain and simple, there's no library I'm aware of (at least open source anyway) that can do this any better than the other.

All that said, this repo is for an IKVM based port, and nobody here would be actually changing/improving the functionality of Tika/PDFBox. You might try their mailing lists, but I can tell you the answer you're going to get: ordering when extracting text is not even in the same real of "exact science."

**Comment by KevM** [comment]
@TechnikEmpire thank you for the excellent insight to the problem presented, and thank you for your continued help with this project.

**Comment by rekhatiwarigeniusminds** [comment]
Thank you so much for reply Jesse. Best Regards,Rekha Patil-Tiwari.Sr. Software Consultant.
Genius Minds Consulting & Services.

**Comment by TechnikEmpire** [comment]
@rekhatiwarigeniusminds No problem. I completely glossed over your question about images. This is due to a deficiency in IKVM itself, and that project has now been abandoned. I'm going to guess that you get a "method not implemented" exception when calling these image reading functions, yes? IKVM leaves some key JDK core methods unimplemented which means PDFBox or anything else for that matter trying to call these same methods will always fail.

**Comment by KevM** [comment]
I believe IKVM dependencies and nugget dependency problems have been fixed. Regarding PCL support if someone needs this please open an issue and we can investigate.
